# Generated by Django 4.0 on 2023-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
