# Generated by Django 4.0 on 2023-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('author', models.CharField(max_length=128, null=True)),
                ('year_publication', models.IntegerField(null=True)),
                ('img_s', models.URLField(null=True)),
                ('img_m', models.URLField(null=True)),
                ('img_l', models.URLField(null=True)),
                ('genres', models.CharField(max_length=512, null=True)),
                ('total_pages', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
