# Generated by Django 4.0 on 2023-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0005_book_publisher_alter_book_author_alter_book_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
