# Generated by Django 4.0 on 2023-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0007_alter_book_author_alter_book_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='top_64_sim',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
