# Generated by Django 4.0 on 2023-05-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0008_book_top_64_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_manager.book'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_manager.user'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
