# Generated by Django 4.0 on 2023-05-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_manager', '0009_rating_book_rating_star_rating_user_alter_rating_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='no', max_length=3)),
                ('user', models.ForeignKey(default=300000, on_delete=django.db.models.deletion.CASCADE, to='books_manager.user')),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=300000, on_delete=django.db.models.deletion.CASCADE, to='books_manager.user'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_manager.book')),
                ('cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_manager.cart')),
            ],
        ),
    ]
